# Generated by Django 4.2.1 on 2023-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_customer_customerproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
