# Generated by Django 4.2.1 on 2023-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customer_address_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_field',
            field=models.CharField(default='Default Value', max_length=100),
        ),
    ]
